[build]
  command = "npm run build:client"
  publish = "dist/static"

[build.environment]
  NODE_VERSION = "20"
  COREPACK_ENABLE = "0"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200